### ISSUE TITLE
Jest

### ISSUE THREAD

**Issue by alexcarpenter** [andybelldesign/npm-uninstall-facebook#1]
https://github.com/facebook/jest

Cannot speak into alternatives but thought i'd add it here.

**Comment by andybelldesign** [comment]
Yeh I’m not overly qualified to make solid recommendations. Will be very open to getting some in from the community though.

**Comment by Haroenv** [comment]
Ava is a good alternative

**Comment by Haroenv** [comment]
No thanks

**Comment by andybelldesign** [comment]
Luckily @m1rp stepped up and put a _tonne_ of alternatives in #22. 

That means we can close this off.
