### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by xgenvn** [andybelldesign/npm-uninstall-facebook#12]
Not sure why you treat the Facebook entity as a whole for the recent issues. 

For me the opensource soul running at FB and their main product issues are not the same things. 

My apology if I'm wrong, but I read this repo description and my feeling is "Oh, Facebook is doing something bad, perhaps we need to start to get rid of their every contribution to the opensource world". 

If this is true, it will be the childish and shallowest reason I have ever seen.

**Comment by andybelldesign** [comment]
They've contributed great stuff to the open source world and it's greatly appreciated. We've got to draw the line somewhere though.

Also this site isn't telling people to _remove_ FB's open source contributions. It's presenting alternatives to those who want to move away from technologies that have benefitted from FB resources.

I y'all want to carry on using FB tech, crack on 👍
