### ISSUE TITLE
Remove GraphQL from the website

### ISSUE THREAD

**Issue by filipdanic** [andybelldesign/npm-uninstall-facebook#13]
There is no reason to boycott the usage of GraphQL, as it is no longer affiliated with Facebook.

Sources:
- https://techcrunch.com/2018/11/06/facebooks-graphql-gets-its-own-open-source-foundation/
- https://www.linuxfoundation.org/press-release/2018/11/intent_to_form_graphql/
- https://foundation.graphql.org/

**Comment by cgatian** [comment]
And the alternative is REST? Lol aww hell naw

**Comment by andybelldesign** [comment]
More than happy to accept PRs for other alternatives, @cgatian...

I want to agree, @filipdanic, but so much Facebook resource has gone into the project pre this change. It's tarnished now.

**Comment by Daniel15** [comment]
> And the alternative is REST? Lol aww hell naw

lol, listing REST as an alternative to GraphQL is like listing `document.createElement` as an alternative to React. 😂

**Comment by andybelldesign** [comment]
_sighs audibly_ 
Cheers, Daniel.

**Comment by isBatak** [comment]
[JSONAPI ](https://jsonapi.org/) is the real alternative, and it needs more attention.
Link to REST specification is nice to have and I think it should stay because it lays out basic ideas behind REST protocol and speaks about core problems in API design.

And, GraphGL will always be associated with Facebook, whatever you guys say.

**Comment by filipdanic** [comment]
I’m not sure how why this association is so terrible, but that’s perhaps where we agree to disagree. :) If GraphQL was still run as a closed governance project under Facebook, I would understand the point of listing it. But as things stand the project is open to all. I think that’s a great thing and the past doesn’t really matter.

If any other not-so-moral tech company open-sourced a brilliant piece of technology and let the community govern it, I would gladly look at it and use it if it solved a major problem for me. I don’t think there’s anything to be gained from boycotting the great work of thousands of non-facebook-affiliated folks who are trying to push technology forward.

You are free to disagree with me, but I’d like to point I’m not really interested in debating this over GitHub issues.

Regardless, even if you keep GraphQL on the site, I feel the new governance model should at least be mentioned. Let people see that information and decide on their own.

As for the question of alternatives, maybe [Falcor](http://netflix.github.io/falcor/) (Netflix) is a viable candidate.

**Comment by andybelldesign** [comment]
> Regardless, even if you keep GraphQL on the site, I feel the new governance model should at least be mentioned. Let people see that information and decide on their own.

I agree wholeheartedly with this and will happily accept PRs.

I’ll mention again that this site isn’t calling for boycotts. It’s providing alternatives to people who want to remove _any_ links with Facebook. Folks are welcome to use whatever they want.

It’s definitely a good thing that GraphQL is properly open now, but the link to Facebook will always be there. We can’t deny that.

**Comment by cgatian** [comment]
Falcor is an alternative!

**Comment by Daniel15** [comment]
I didn't know about JSONAPI and Falcor... They look closer to the model that GraphQL provides and are probably the most suitable alternatives. Thanks for the links!

**Comment by andybelldesign** [comment]
I am shocked and very glad that this thread actually turned out productive considering the starting remarks. 

I’ll close this and merge the PR that contains JSONAPI.
