### ISSUE TITLE
Babel

### ISSUE THREAD

**Issue by Daniel15** [andybelldesign/npm-uninstall-facebook#18]
I see Babel and Babylon in your `package-lock.json`. Babel (at least 5.x and 6.x) was primarily developed by a Facebook employee. 😄

**Comment by andybelldesign** [comment]
So, the premise of the site (I must write some simpler, easier to understand copy) is that the site provides _alternatives_. It would be very silly to just rip dependencies out willy-nilly, wouldn’t it, Daniel? Especially dependencies of the SSG that powers the site.

So (possibly wasting my breathe based on your other “contributions”), do you happen to know any alternatives? I’d like to think you might have something, now that you’ve opened an issue.

**Comment by Daniel15** [comment]
Alternatives to Babel? I guess only using JS syntax that all browsers support, to avoid transpiling.

Sorry for the issue, I agree that I probably shouldn't have opened it.

**Comment by andybelldesign** [comment]
No worries. It’s easy to get caught up in stuff.

We’re all in this together, remember.
