### ISSUE TITLE
Why Gatsby?

### ISSUE THREAD

**Issue by SaraVieira** [andybelldesign/npm-uninstall-facebook#30]
Hey !

I love this! From what I know Gatsby is its own company

Is it because it's based on react ?

**Comment by SaraVieira** [comment]
Also you can replace react in Gatsby with preact
https://www.gatsbyjs.org/packages/gatsby-plugin-preact/

**Comment by andybelldesign** [comment]
Hey! Yes, exactly that. 

It is good to see that a Preact plugin is about as an option, though.

**Comment by SaraVieira** [comment]
Makes sense! 

Closing 

Do you want a react native alternatives?

**Comment by andybelldesign** [comment]
Holy moly, that would be _super_ handy if you could. Both that it'll be awesome to have on the site, but I'm also v-interested (slight Vue pun) in seeing what else is about!
